### ISSUE TITLE
Update server configuration props

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/documentation#171]

**Comment by cyyynthia** [comment]
I've looked a bit into the source code to gather all the current config props and start working on a PR to add the currently missing flags. While I have a relatively good understanding of what most flags do from a bit of guess work and poking at the source code, I couldn't understand what the `tolgee.import` flags are for 🤔

In addition to adding missing flags, considering Spring's [relaxed binding](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.typesafe-configuration-properties.relaxed-binding), it may be a good idea to also write all the properties in dashed-case, for consistency (e.g. `tolgee.file-storage.fs-data-path` instead of `tolgee.file-storage.fsDataPath`)

**Comment by JanCizmar** [comment]
>  I couldn't understand what the tolgee.import props are for

- Using `dir` prop you can specify a dir, where exported .jsons are stored. It then automatically imports this dir's subdirs as project with name of particular subdir. We are using this for e2e testing of js integrations, so we don't need to manually import the data before the actual testing. It's also useful for development. Sometimes, I just need to delete my local DB and start fresh. This provides the data on startup.
- When the `create-implicit-api-key` prop is set to `true` it also creates a API key for the imported project like `${projectName}-${userAccount.name}-imported-project-implicit`, which again, we need for e2e tests of js integrations

> it may be a good idea to also write all the properties in dashed-case, for consistency

You're right. Feel free to fix it. 🚀 

Thanks a lot ❤️
